sudo: required
services:
  - docker

before_install:
  - docker build -t shanem123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shanem123/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: docker-react
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-306511242966"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
